import { db } from './db';
import { loyaltyRewards, achievements } from '@shared/schema-mysql';
import { eq } from 'drizzle-orm';

const DEFAULT_REWARDS = [
  {
    id: crypto.randomUUID(),
    title: 'Envío Gratis',
    description: 'Envío gratuito en tu próximo pedido en Soria',
    pointsCost: 500,
    type: 'shipping_discount',
    value: 'free_shipping',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Válido solo en Soria. Expira en 30 días.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: '15% Descuento',
    description: 'Descuento del 15% en cualquier pedido en Soria',
    pointsCost: 750,
    type: 'percent_discount',
    value: '15',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Mínimo pedido 15€. Válido en Soria.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: '5€ Cashback',
    description: 'Recibe 5 euros de descuento en tu próximo pedido',
    pointsCost: 1000,
    type: 'fixed_discount',
    value: '5',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Mínimo pedido 20€. Válido 30 días.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: '20% Descuento VIP',
    description: 'Descuento exclusivo para miembros Gold y Platinum',
    pointsCost: 1500,
    type: 'percent_discount',
    value: '20',
    minTier: 'gold',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Exclusivo Gold/Platinum. Mínimo 25€.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: '10€ Cashback',
    description: 'Recibe 10 euros de descuento en tu próximo pedido',
    pointsCost: 2000,
    type: 'fixed_discount',
    value: '10',
    minTier: 'silver',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Mínimo pedido 30€. Válido 30 días.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: '10% de descuento',
    description: 'Obtén un 10% de descuento en tu próximo pedido',
    pointsCost: 500,
    type: 'percent_discount',
    value: '10',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Válido en cualquier pedido.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: 'Envío gratis',
    description: 'Envío gratis en tu próximo pedido',
    pointsCost: 300,
    type: 'shipping_discount',
    value: 'free_shipping',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Válido 15 días.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: 'Bebida gratis',
    description: 'Obtén una bebida gratis valorada hasta 5€',
    pointsCost: 750,
    type: 'free_item',
    value: 'drink_5',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Hasta 5€ de valor.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: '15% de descuento',
    description: '15% de descuento en pedidos mayores a 20€',
    pointsCost: 1000,
    type: 'percent_discount',
    value: '15',
    minTier: 'bronze',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Solo pedidos >20€.',
    isAvailable: true,
    currentRedemptions: 0,
  },
  {
    id: crypto.randomUUID(),
    title: 'Cena gratis',
    description: 'Una cena completa gratis (hasta 30€)',
    pointsCost: 3000,
    type: 'free_item',
    value: 'dinner_30',
    minTier: 'gold',
    maxRedemptions: null,
    expiresAt: null,
    imageUrl: null,
    terms: 'Hasta 30€. Solo Gold/Platinum.',
    isAvailable: true,
    currentRedemptions: 0,
  },
];

const DEFAULT_ACHIEVEMENTS = [
  {
    id: crypto.randomUUID(),
    name: 'Primer Pedido',
    description: 'Realiza tu primer pedido',
    icon: '🎯',
    requirementType: 'order_count',
    requirementValue: 1,
    rewardPoints: 50,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Cliente Fiel',
    description: 'Completa 5 pedidos',
    icon: '💚',
    requirementType: 'order_count',
    requirementValue: 5,
    rewardPoints: 100,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Pedidor',
    description: 'Completa 10 pedidos',
    icon: '⭐',
    requirementType: 'order_count',
    requirementValue: 10,
    rewardPoints: 200,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'VIP',
    description: 'Completa 25 pedidos',
    icon: '👑',
    requirementType: 'order_count',
    requirementValue: 25,
    rewardPoints: 500,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Gastador',
    description: 'Gasta 100€ en total',
    icon: '💰',
    requirementType: 'total_spent',
    requirementValue: 100,
    rewardPoints: 100,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Gran Gastador',
    description: 'Gasta 500€ en total',
    icon: '🏆',
    requirementType: 'total_spent',
    requirementValue: 500,
    rewardPoints: 300,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Mega Gastador',
    description: 'Gasta 2000€ en total',
    icon: '💎',
    requirementType: 'total_spent',
    requirementValue: 2000,
    rewardPoints: 1000,
    isActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: 'Critico',
    description: 'Escribe 3 reseñas',
    icon: '📝',
    requirementType: 'review_count',
    requirementValue: 3,
    rewardPoints: 75,
    isActive: true,
  },
];

export async function seedGamification() {
  try {
    const existingRewards = await db.select().from(loyaltyRewards).limit(1);
    if (existingRewards.length === 0) {
      await db.insert(loyaltyRewards).values(DEFAULT_REWARDS);
      console.log('✅ Gamification rewards seeded');
    }

    const existingAchievements = await db.select().from(achievements).limit(1);
    if (existingAchievements.length === 0) {
      await db.insert(achievements).values(DEFAULT_ACHIEVEMENTS);
      console.log('✅ Gamification achievements seeded');
    }
  } catch (error) {
    console.error('❌ Gamification seed error:', error);
  }
}